language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r test-requirements.txt
  - pip install coveralls
script:
  - coverage run -m nose
  - coverage xml
  - diff-cover coverage.xml
  - diff-quality --violation=pep8
  - diff-quality --violation=pylint
after_success:
  - coveralls
